<a href="http://www.foamtotem.org/gallery/MikesLotusElise"><img src="/daily/elise_thumb.jpg" border="0" align="right"></a>
Don't click on it yet! Guess what this is a picture of...
<p style="text-align:right;font-size:10px;clear:right"><a href="javascript:HaloScan('20050925_9_121238');" target="_self"><script type="text/javascript">postCount('20050925_9_121238');</script></a></p>