<div class="title">Nightmare Images</div>
	<div class="gallery_20100513_1_135300"><img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/FizcqjqCyAbEdDgaFrGpdukdkBHdBigHepIdbzwJmJDIbiFtIqCoImxjEltJ/4zdzislaw-beksinski-0509-236x300.jpg.scaled500.jpg" width="236" height="300" />
<a href="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/BhpBEHqDhBBsIqDEgJhsBfpulJGilfemEAuJeGFonIHkiEHxsrFBjotmhGCf/am_zdzislaw_beksinski095_1976.jpg.scaled1000.jpg"><img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/BhpBEHqDhBBsIqDEgJhsBfpulJGilfemEAuJeGFonIHkiEHxsrFBjotmhGCf/am_zdzislaw_beksinski095_1976.jpg.scaled500.jpg" width="500" height="580" /></a>
<a href="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/DwGpxkvzsGbxjaeldHuuvAcbkuwieDAFvAvCkBJphinlymhqqogjisCoEtHl/lj_ZdzislawBeksinski042.jpg.scaled1000.jpg"><img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/DwGpxkvzsGbxjaeldHuuvAcbkuwieDAFvAvCkBJphinlymhqqogjisCoEtHl/lj_ZdzislawBeksinski042.jpg.scaled500.jpg" width="500" height="613" /></a>
<img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/lIIacvwgyGqfIJHuHwDwlcndAlaHcfmyEFBwqgpBCDAjAhgmenyxlgsHJHvt/zdzislaw_beksinski_003.jpg.scaled500.jpg" width="461" height="550" />
<a href="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/wrnHkrqmBvIrFCHBuciFBkbBnnHClAnBfyEcpyfwBIvbEaGsABuFoCgDzbgg/zdzislaw_beksinski_111.jpg.scaled1000.jpg"><img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/wrnHkrqmBvIrFCHBuciFBkbBnnHClAnBfyEcpyfwBIvbEaGsABuFoCgDzbgg/zdzislaw_beksinski_111.jpg.scaled500.jpg" width="500" height="631" /></a>
<a href="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/bnGotiaGkquggaxwrzmasrFvHClzEBmwHubykEFckHscDnHGpHitbmAzHIEF/zdzislaw_beksinski_115.jpg.scaled1000.jpg"><img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/bnGotiaGkquggaxwrzmasrFvHClzEBmwHubykEFckHscDnHGpHitbmAzHIEF/zdzislaw_beksinski_115.jpg.scaled500.jpg" width="500" height="589" /></a>
<a href="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/CpsoIvhFBuACCwdgcpFjepoenbCebDzfsefFDbidhofeoAoIzqHzzDhxnxsI/zdzislaw_beksinski_1978.jpg.scaled1000.jpg"><img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/CpsoIvhFBuACCwdgcpFjepoenbCebDzfsefFDbidhofeoAoIzqHzzDhxnxsI/zdzislaw_beksinski_1978.jpg.scaled500.jpg" width="500" height="611" /></a>
<a href="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/ajivzpdHBFkkjtnfuliDcqEdavzJtFHaqfBFDqHcgkFhngrlnBBtzElvACpf/zdzislaw_beksinski_120.jpg.scaled1000.jpg"><img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/ajivzpdHBFkkjtnfuliDcqEdavzJtFHaqfBFDqHcgkFhngrlnBBtzElvACpf/zdzislaw_beksinski_120.jpg.scaled500.jpg" width="500" height="632" /></a>
<a href="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/fafDrhllAGfHFrAHleoldEnmukrkHuuryvkqburIqaErhfqnIfnFBqbmcxHi/zdzislaw_beksinski_1980_3.jpg.scaled1000.jpg"><img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/fafDrhllAGfHFrAHleoldEnmukrkHuuryvkqburIqaErhfqnIfnFBqbmcxHi/zdzislaw_beksinski_1980_3.jpg.scaled500.jpg" width="500" height="436" /></a>
<a href="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/fEdaEcFhbpcuIwqIfIpdAeEdexDgoaHEEABdJnfzpenaJItwCsiaCiskvupp/zdzislaw_beksinski_103.jpg.scaled1000.jpg"><img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/fEdaEcFhbpcuIwqIfIpdAeEdexDgoaHEEABdJnfzpenaJItwCsiaCiskvupp/zdzislaw_beksinski_103.jpg.scaled500.jpg" width="500" height="427" /></a>
<a href="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/ytagqrfvtvJqyFqvDreihnEaGmieiEjbsoyIwCGApfimmcsgGtEytpowqtrq/zdzislaw_beksinski_1983_3.jpg.scaled1000.jpg"><img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/ytagqrfvtvJqyFqvDreihnEaGmieiEjbsoyIwCGApfimmcsgGtEytpowqtrq/zdzislaw_beksinski_1983_3.jpg.scaled500.jpg" width="500" height="633" /></a>
<img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/JHgraIHBErEeiifpdohJtzAdzfDjrEGpzEIikDzdogdxcxrveGueCvtDizms/zdzislaw_beksinski_018.jpg.scaled500.jpg" width="397" height="540" />
<a href="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/lDukzeftpeqdoblGhjiumDGpwziCbHopuzqEDfjCfxmoCzdymFmsDfpazDan/zdzislaw_beksinski_P0733_990213.jpg.scaled1000.jpg"><img src="http://posterous.com/getfile/files.posterous.com/temp-2010-05-13/lDukzeftpeqdoblGhjiumDGpwziCbHopuzqEDfjCfxmoCzdymFmsDfpazDan/zdzislaw_beksinski_P0733_990213.jpg.scaled500.jpg" width="500" height="375" /></a><a href="http://posniewski.posterous.com/nightmare-images">See and download the full gallery on posterous</a></div>
<p><a href="http://www.gnosis.art.pl/iluminatornia/sztuka_o_inspiracji/zdzislaw_beksinski/zdzislaw_beksinski.htm">ZDZISŁAW BEKSIŃSKI</a> had some very dark visions... and that was before this:</p>
<p>From <a href="http://en.wikipedia.org/wiki/Zdzis%C5%82aw_Beksi%C5%84ski">Wikipedia</a>:</p>
<p><span style="font-family:sans-serif;font-size:10px;line-height:15px"> </span></p>
<blockquote>
<p style="margin-top:0.4em;margin-right:0px;margin-bottom:0.5em;margin-left:0px;line-height:1.5em">The late 1990s were a very trying time for Beksiński. His wife, Zofia, died in 1998; a year later, on Christmas Eve 1999, his son Tomasz (a popular radio presenter, music journalist and movie translator) committed suicide. Beksiński discovered his son's body. Unable to come to terms with his son's death, he kept an envelope "For Tomek in case I kick the bucket" pinned to his wall.</p>
<p style="margin-top:0.4em;margin-right:0px;margin-bottom:0.5em;margin-left:0px;line-height:1.5em">On 21 February 2005, Beksiński was found dead in his flat in Warsaw with 17 stab wounds on his body; two of the wounds were determined to have been fatal. Robert Kupiec (the teenage son of his long time caretaker), who later pleaded guilty, and a friend were arrested shortly after the crime. On 9 November 2006 Robert Kupiec was condemned to 25 years of prison, and his accomplice, Łukasz Kupiec, to 5 years by the court of Warsaw. Before his death, Beksiński refused a small loan to Robert Kupiec (a few hundred złotys; approximately $100).</p>
<p style="margin-top:0.4em;margin-right:0px;margin-bottom:0.5em;margin-left:0px;line-height:1.5em">[...]</p>
<p style="margin-top:0.4em;margin-right:0px;margin-bottom:0.5em;margin-left:0px;line-height:1.5em">Although Beksiński's art was often grim, he himself was known to be a pleasant person who took enjoyment from conversation and had a keen sense of humor. He was exceptionally modest and somewhat shy, avoiding public events such as the openings of his own exhibitions. He credited music as his main source of inspiration.</p>
</blockquote>
<p> </p>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="/js/galleria.js"></script>
<script>
	Galleria.loadTheme('/js/galleria_themes/classic/galleria.classic.js');
	$(".gallery_20100513_1_135300").galleria();
</script>
<p class="comments"><a href="javascript:HaloScan('20100513_1_135300');" target="_self"><script type="text/javascript">postCount('20100513_1_135300');</script></a></p>